# NumPy

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/logo.png" width=150>

In this lesson we will learn the basics of numerical analysis using the NumPy package.

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/numpy.png" width=300>




# NumPy basics

In [9]:
import numpy as np

In [10]:
# Set seed for reproducibility（可再现性，这句话就是设置了seed，让随机数可重复出现）
np.random.seed(seed=1234)

In [11]:
# Scalars
x = np.array(6) # scalar
print ("x: ", x)
# Number of dimensions
print ("x ndim: ", x.ndim)
# Dimensions
print ("x shape:", x.shape)
# Size of elements
print ("x size: ", x.size)
# Data type
print ("x dtype: ", x.dtype)

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int32


In [12]:
# 1-D Array
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the float datatype

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


In [13]:
# 3-D array (matrix)
x = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
x ndim:  3
x shape: (1, 3, 3)
x size:  9
x dtype:  int32


In [14]:
# Functions
print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2)))
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
* Parameters:

    * N : int:  Number of rows in the output.

    * M : int, optional: Number of columns in the output. If None, defaults to N.

    * k : int, optional: Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

    * dtype : data-type, optional: Data-type of the returned array.

    * order : {‘C’, ‘F’}, optional: Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.

* Returns:	
    * I : ndarray of shape (N,M), An array where all elements are equal to zero, except for the k-th diagonal, whose values are equal to one.

# Indexing

In [15]:
# Indexing
x = np.array([1, 2, 3])
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x[0]:  1
x:  [0 2 3]


In [29]:
# Slicing
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x.shape", x.shape)   # This line is added by me.
print ("x column 1: ", x[:, 1]) 
print ("x row 0: ", x[0, :]) 
print ("x rows 0,1,2 & cols 1,2: \n", x[:3, 1:3]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x.shape (3, 4)
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1,2 & cols 1,2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [31]:
# Integer array indexing
print (x)
rows_to_get = np.arange(len(x))
print ("rows_to_get: ", rows_to_get)
print (type(rows_to_get)) # This line is added by me.
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
print ("indexed values: ", x[rows_to_get, cols_to_get]) # 整数数组索引，在这里是x[[0, 1, 2], [0, 2, 1]]得到的结果是[x[0, 0], x[1, 2], x[2, 1]]

# This part is added by me. 数组寻址的妙用！可以很简单地给数组寻址找到的元素赋值！
x[rows_to_get, cols_to_get] = [2, 8, 11]
print (x)
x[rows_to_get, cols_to_get] = 0
print (x)

[[ 2  2  3  4]
 [ 5  6  8  8]
 [ 9 11 11 12]]
rows_to_get:  [0 1 2]
<class 'numpy.ndarray'>
cols_to_get:  [0 2 1]
indexed values:  [ 2  8 11]
[[ 2  2  3  4]
 [ 5  6  8  8]
 [ 9 11 11 12]]
[[ 0  2  3  4]
 [ 5  6  0  8]
 [ 9  0 11 12]]


In [25]:
# Boolean array indexing
x = np.array([[1,2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2)
print ("x[x > 2]:\n", x[x > 2])

# This part is added by me. 数组寻址的妙用！可以很简单地给数组寻址找到的元素赋值！
x[x > 2] = -2
print(x)

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]
[[ 1  2]
 [-2 -2]
 [-2 -2]]


# Array math

In [12]:
# Basic math
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/matrix.png" width=400>


In [13]:
# Dot product
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
print (a.dot(b))

[[ 58.  64.]
 [139. 154.]]


In [35]:
# Sum across a dimension
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum by col: ", np.sum(x, axis=0)) # add numbers in each column
print ("sum by row: ", np.sum(x, axis=1)) # add numbers in each row

# This part is added by me.
# 上面这个部分讲得不透彻，np.sum(x, axis=0)的含义应该是对x的第0维的元素相加，也就是上面的[1, 2] + [3, 4]，它们是x的第0维，
# 即通过一次寻址可以找到，如x[1]找到的是[3, 4]. 而np.sum(x, axis=1)是取出x的第一维元素相加，x的第一维元素是x[1, 0]和x[1, 1]这样的元素，
# 相加就是3和7，下面这个例子更为清晰
x = np.array([[[1, 1], [2, 2]],
              [[3, 3], [4, 4]]])
print("\n\n", x)
print ("sum by axis = 0: \n", np.sum(x, axis=0)) # add x[0], x[1]
print ("sum by axis = 1: \n", np.sum(x, axis=1)) # [[x[0, 0] + x[0, 1]],
                                               # [x[1, 0] + x[1, 1]]]

[[1 2]
 [3 4]]
sum all:  10
sum by col:  [4 6]
sum by row:  [3 7]


 [[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]
sum by axis = 0: 
 [[4 4]
 [6 6]]
sum by axis = 1: 
 [[3 3]
 [7 7]]


In [15]:
# Transposing
print ("x:\n", x)
print ("x.T:\n", x.T)

x:
 [[1 2]
 [3 4]]
x.T:
 [[1 3]
 [2 4]]


# Advanced

In [38]:
# Tile
# Numpy的 tile() 函数，就是将原矩阵横向、纵向地复制。tile 是瓷砖的意思，顾名思义，这个函数就是把数组像瓷砖一样铺展开来。
x = np.array([[1,2], [3,4]])
y = np.array([5, 6])
addent = np.tile(y, (len(x), 1)) # len(x) = 2, 把y铺展成2, 1的形状，相当于以y为基本单元，变成2行1列的由y组成的矩阵！若是传入的tuple是3，4，可以看一下结果
print ("addent: \n", addent)
z = x + addent
print ("z:\n", z)

# This part is added by me.
print ("\n\n把y当基本元素铺成3 * 4\n", np.tile(y, (3, 4)))

addent: 
 [[5 6]
 [5 6]]
z:
 [[ 6  8]
 [ 8 10]]


把y当基本元素铺成3 * 4
 [[5 6 5 6 5 6 5 6]
 [5 6 5 6 5 6 5 6]
 [5 6 5 6 5 6 5 6]]


In [17]:
# Broadcasting
x = np.array([[1,2], [3,4]])
y = np.array([5, 6])
z = x + y
print ("z:\n", z)

z:
 [[ 6  8]
 [ 8 10]]


In [18]:
# Reshaping
x = np.array([[1,2], [3,4], [5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (2, 3))
print ("y.shape: ", y.shape)
print ("y: \n", y)

[[1 2]
 [3 4]
 [5 6]]
x.shape:  (3, 2)
y.shape:  (2, 3)
y: 
 [[1 2 3]
 [4 5 6]]


In [19]:
# Removing dimensions
x = np.array([[[1,2,1]],[[2,2,3]]])
print ("x.shape: ", x.shape)
y = np.squeeze(x, 1) # squeeze dim 1
print ("y.shape: ", y.shape) 
print ("y: \n", y)

x.shape:  (2, 1, 3)
y.shape:  (2, 3)
y: 
 [[1 2 1]
 [2 2 3]]


In [20]:
# Adding dimensions
x = np.array([[1,2,1],[2,2,3]])
print ("x.shape: ", x.shape)
y = np.expand_dims(x, 1) # expand dim 1
print ("y.shape: ", y.shape) 
print ("y: \n", y)

x.shape:  (2, 3)
y.shape:  (2, 1, 3)
y: 
 [[[1 2 1]]

 [[2 2 3]]]


# Additional resources

You don't have to memorize anything here and we will be taking a closer look at NumPy in the later lessons. If you are curious about more checkout the [NumPy reference manual](https://docs.scipy.org/doc/numpy-1.15.1/reference/).