# PyTorch

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/logo.png" width=150>

In this lesson we'll learn about PyTorch which is a machine learning library used to build dynamic neural networks. We'll learn about the basics, like creating and using Tensors, in this lesson but we'll be making models with it in the next lesson.

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/pytorch.png" width=300>

# Tensor basics

In [2]:
# Load PyTorch library
!pip3 install torch
# Or you can use mirror in qinghua, but in Windows it's hard to do it! Because you have no power.
# !pip install torch --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple 

In [3]:
import numpy as np
import torch

In [4]:
# Creating a zero tensor
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [5]:
# Creating a random tensor
x = torch.randn(2, 3) # normal distribution (rand(2,3) -> uniform distribution)
print (x)

tensor([[ 0.7434, -1.0611, -0.3752],
        [ 0.2613, -1.7051,  0.9118]])


In [6]:
# Zero and Ones tensor
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
# List → Tensor
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
# NumPy array → Tensor
x = torch.from_numpy(np.random.rand(2, 3))
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[0.0372, 0.6757, 0.9554],
        [0.5651, 0.2336, 0.8303]], dtype=torch.float64)


In [9]:
# Changing tensor type
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor operations

In [10]:
# Addition
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.5650, -0.0173,  1.1263],
        [ 3.4274,  1.3610, -0.9262]])


In [11]:
# Dot product
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[ 1.3294, -2.4559],
        [-0.4337,  4.9667]])


In [12]:
# Transpose
x = torch.randn(2, 3)
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0257, -0.5716, -0.9207],
        [-1.0590,  0.2942, -0.7114]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.0257, -1.0590],
        [-0.5716,  0.2942],
        [-0.9207, -0.7114]])


In [13]:
# Reshape
z = x.view(3, 2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.0257, -0.5716],
        [-0.9207, -1.0590],
        [ 0.2942, -0.7114]])


In [14]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("Size: {}".format(x.shape)) 
print("Values: \n{}\n".format(x))
a = x.view(x.size(1), -1)
print("Size: {}".format(a.shape)) 
print("Values: \n{}\n".format(a))
# 这里是把(2, 3, 4)->(3, 2, 4)，要这样变化就应该用1轴的元素重组成0轴的元素，[1,1,1,1]和[10,10,10,10]重组为[[1,1,1,1], [10,10,10,10]]
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape)) 
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape)) 
print("Values: \n{}".format(c))

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [9]:
# Dimensional operations
x = torch.tensor([[1, 1, 1], [2, 2, 2]])    # 这里用Tensor()函数的话，生成的x默认是float类型的，用tensor则是long类型
print (x.type(), "\n\n")                    # This line is added by me.

print("Values: \n{}".format(x))
y = torch.sum(x, dim=0) # add each row's value for every column
print("Values: \n{}".format(y))
z = torch.sum(x, dim=1) # add each columns's value for every row
print("Values: \n{}".format(z))

torch.LongTensor 


Values: 
tensor([[1, 1, 1],
        [2, 2, 2]])
Values: 
tensor([3, 3, 3])
Values: 
tensor([3, 6])


# Indexing, Splicing and Joining

In [10]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[ 0.4303, -0.5946, -0.8464,  1.2557],
        [ 1.1817, -0.8095, -0.0647,  0.2797],
        [-0.0375, -1.0746, -0.5206,  0.2409]])
x[:1]: 
tensor([[ 0.4303, -0.5946, -0.8464,  1.2557]])
x[:1, 1:3]: 
tensor([[-0.5946, -0.8464]])


In [17]:
# Select with dimensional indicies
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # values from column 0 & 2
print("Values: \n{}".format(chosen)) 
row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices] # values from (0, 0) & (2, 1) 与numpy的整数数组索引的方式一样，反而是index_select在numpy教程里没有
print("Values: \n{}".format(chosen)) 

Values: 
tensor([[ 0.0720,  0.4266, -0.5351],
        [ 0.9672,  0.3691, -0.7332]])
Values: 
tensor([[ 0.0720, -0.5351],
        [ 0.9672, -0.7332]])
Values: 
tensor([ 0.0720, -0.7332])


In [12]:
# Concatenation
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim = 0) # stack by rows (dim=1 to stack by columns)
print("Values: \n{}".format(y))

Values: 
tensor([[ 1.4160,  1.0776,  0.3112],
        [ 1.2137, -0.4977, -1.4881]])
Values: 
tensor([[ 1.4160,  1.0776,  0.3112],
        [ 1.2137, -0.4977, -1.4881],
        [ 1.4160,  1.0776,  0.3112],
        [ 1.2137, -0.4977, -1.4881]])


# Gradients

In [26]:
# Tensors with gradient bookkeeping
x = torch.rand(3, 4, requires_grad = False)

x.requires_grad = True        # This line is added by me. The default value above is requires_grad = True

y = 3 * x + 2
z = y.mean()

# This part is added by me.
print (z.type())
print (z)

z.backward() # z has to be scalar
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

torch.FloatTensor
tensor(3.2328, grad_fn=<MeanBackward1>)
Values: 
tensor([[0.4241, 0.4667, 0.5611, 0.3788],
        [0.8638, 0.2878, 0.2257, 0.2397],
        [0.5680, 0.5012, 0.1177, 0.2968]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


* $ y = 3x + 2 $
* $ z = \sum{y}/N $
* $ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(y)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

# CUDA tensors

In [20]:
# Is CUDA available?
print (torch.cuda.is_available())

True


If the code above return False, then go to `Runtime` → `Change runtime type` and select `GPU` under `Hardware accelerator`. 

In [23]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [24]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))

Type: torch.cuda.FloatTensor
